# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pause_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PauseMenu(object):
    def setupUi(self, PauseMenu):
        PauseMenu.setObjectName("PauseMenu")
        PauseMenu.resize(230, 240)
        self.centralwidget = QtWidgets.QWidget(PauseMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 210, 60))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 80, 210, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 150, 210, 60))
        self.pushButton_3.setObjectName("pushButton_3")
        PauseMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PauseMenu)
        self.statusbar.setObjectName("statusbar")
        PauseMenu.setStatusBar(self.statusbar)

        self.retranslateUi(PauseMenu)
        QtCore.QMetaObject.connectSlotsByName(PauseMenu)

    def retranslateUi(self, PauseMenu):
        _translate = QtCore.QCoreApplication.translate
        PauseMenu.setWindowTitle(_translate("PauseMenu", "MainWindow"))
        self.pushButton.setText(_translate("PauseMenu", "Resume"))
        self.pushButton_2.setText(_translate("PauseMenu", "Settings"))
        self.pushButton_3.setText(_translate("PauseMenu", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PauseMenu = QtWidgets.QMainWindow()
    ui = Ui_PauseMenu()
    ui.setupUi(PauseMenu)
    PauseMenu.show()
    sys.exit(app.exec_())
